var regras = {
    R1: [{
        "sim": "R2",
        "nao": "R3",
        "pergunta": "É mulher?",
        "foto_sim": null,
        "foto_nao": null,
    }],
    R2: [{
        "sim": "R4",
        "nao": "R5",
        "pergunta": "Tem Cabelo Castanho?",
        "foto_sim": null,
        "foto_nao": null,
    }],
    R3: [{
        "sim": "R6",
        "nao": "R7",
        "pergunta": "Tem Cabelo Branco?",
        "foto_sim": null,
        "foto_nao": null,
    }],
    R4: [{
        "sim": "R8",
        "nao": "R9",
        "pergunta": "É do Departamento de Computação?",
        "foto_sim": null,
        "foto_nao": null,
    }],
    R5: [{
        "sim": "R10",
        "nao": "Ivete",
        "pergunta": "É do Departamento de Computação?",
        "foto_sim": null,
        "foto_nao": "ivete",
    }],
    R6: [{
        "sim": "R12",
        "nao": "Julião",
        "pergunta": "É do Departamento de Computação?",
        "foto_sim": null,
        "foto_nao": "juliao",
    }],
    R7: [{
        "sim": "R14",
        "nao": "R15",
        "pergunta": "É do Departamento de Computação?",
        "foto_sim": null,
        "foto_nao": null,
    }],
    R8: [{
        "sim": "Andréa",
        "nao": "Márcia",
        "pergunta": "Usa óculos?",
        "foto_sim": "andrea",
        "foto_nao": "marcia",
    }],
    R9: [{
        "sim": "R18",
        "nao": "Eliana",
        "pergunta": "É do Departamento de Matemática?",
        "foto_sim": null,
        "foto_nao": "eliana",
    }],
    R10: [{
        "sim": "Simone",
        "nao": "Patrícia",
        "pergunta": "É exclusiva da Unesp?",
        "foto_sim": "simone",
        "foto_nao": "patricia",
    }],
    R12: [{
        "sim": "Humberto",
        "nao": "R23",
        "pergunta": "Tem bigode?",
        "foto_sim": "humberto",
        "foto_nao":  null,
    }],
    R14: [{
        "sim": "R24",
        "nao": "R25",
        "pergunta": "É exclusivo da Unesp?",
        "foto_sim": null,
        "foto_nao": null,
    }],
    R15: [{
        "sim": "Chico",
        "nao": "Toninho",
        "pergunta": "Usa óculos?",
        "foto_sim": "chico",
        "foto_nao": "toninho",
    }],
    R18: [{
        "sim": "Tati",
        "nao": "Adriana",
        "pergunta": "Usa óculos?",
        "foto_sim": "tati",
        "foto_nao": "adriana",
    }],
    R23: [{
        "sim": "R30",
        "nao": "R31",
        "pergunta": "É alto?",
        "foto_sim": null,
        "foto_nao": null,
    }],
    R24: [{
        "sim": "R32",
        "nao": "R33",
        "pergunta": "É alto?",
        "foto_sim": null,
        "foto_nao": null,
    }],
    R25: [{
        "sim": "Kelton",
        "nao": "Kléber",
        "pergunta": "Tem bigode?",
        "foto_sim": "kelton",
        "foto_nao": "kleber",
    }],
    R30: [{
        "sim": "Sacoman",
        "nao": "Marar",
        "pergunta": "Usa óculos?",
        "foto_sim": "sacoman",
        "foto_nao": "marar",
    }],
    R31: [{
        "sim": "Morgado",
        "nao": "Remo",
        "pergunta": "Usa óculos?",
        "foto_sim": "morgado",
        "foto_nao": "remo",
    }],
    R32: [{
        "sim": "Black",
        "nao": "R41",
        "pergunta": "Usa óculos?",
        "foto_sim": "black",
        "foto_nao": null,
    }],
    R33: [{
        "sim": "Wilson",
        "nao": "R43",
        "pergunta": "É japonês?",
        "foto_sim": "wilson",
        "foto_nao": null,
    }],
    R41: [{
        "sim": "Nilceu",
        "nao": "Sementille",
        "pergunta": "Dá aula de Banco de Dados?",
        "foto_sim": "nilceu",
        "foto_nao": null,
    }],
    R43: [{
        "sim": "R46",
        "nao": "Papa",
        "pergunta": "Usa óculos?",
        "foto_sim": null,
        "foto_nao": "papa",
    }],
    R46: [{
        "sim": "Renê",
        "nao": "Perea",
        "pergunta": "Dá aula de técnicas de programação?",
        "foto_sim": "rene",
        "foto_nao": "perea",
    }],
};
